apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: keda
            repoURL: https://github.com/AbeYuki/manifest.git
            path: ./keda/production
            namespace: keda
            plugin: kustomize-helmcharts
            autoSync: true
            syncOptions: 
              - CreateNamespace=true
              - ServerSideApply=true


  template:
    metadata:
      name: "{{ .name }}"
      namespace: argocd
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .namespace }}"
      source:
        repoURL: "{{ .repoURL }}"
        targetRevision: HEAD
        path: "{{ .path }}"
  templatePatch: |
    spec:
      source:
        {{- if .plugin }}
        plugin:
          name: "{{ .plugin }}"
        {{- end }}
      {{- if or .autoSync .syncOptions }}
      syncPolicy:
        {{- if .autoSync }}
        automated:
          prune: true
          selfHeal: true
        {{- end }}
        {{- if .syncOptions }}
        syncOptions:
        {{- range .syncOptions }}
          - {{ . }}
        {{- end }}
        {{- end }}
      {{- end }}